---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  client_rb:
    audit_mode: :enabled

platforms:
  - name: windows-2008R2
    driver:
      box: windows-2008r2-net451
      gui: false

suites:
  - name: server
    run_list:
      - recipe[verify-octo::server]
    attributes:
  - name: tentacle
    run_list:
      - recipe[verify-octo::tentacle]
    attributes:
