---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.4.1
  client_rb:
    audit_mode: :enabled

platforms:
  - name: windows-2008R2-cvent

suites:
  - name: server
    run_list:
      - recipe[verify-octo::server]
    attributes:
  - name: tentacle
    run_list:
      - recipe[verify-octo::tentacle]
    attributes:
